#!/usr/bin/env python3
"""
Download the most common Swedish words and generate src/commonSwedishWords.js

Source: hermitdave/FrequencyWords (OpenSubtitles 2018 frequency list)
  https://github.com/hermitdave/FrequencyWords

The list is ordered by frequency (most common first). We keep the top words,
skip anything that isn't a plain Swedish word, and filter out a blocklist of
profanity/adult words so the reading game stays appropriate for young children.

Output: src/commonSwedishWords.js exporting COMMON_SWEDISH_WORDS (ordered array).

Run: python3 download_common_swedish_words.py
"""

import re
import sys
import urllib.request

SOURCE_URL = "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/sv/sv_50k.txt"
OUTPUT_FILE = "src/commonSwedishWords.js"
TARGET_COUNT = 1000

# Only allow plain lowercase Swedish letters (no digits, punctuation, English contamination).
VALID_WORD = re.compile(r"^[a-zåäö]+$")

# Profanity / adult / otherwise inappropriate words to keep out of a children's
# reading game. OpenSubtitles data contains plenty of these near the top.
BLOCKLIST = {
    "fan", "faen", "jävla", "jävlar", "jävel", "jävla", "djävla", "djävlar",
    "helvete", "helvetet", "satan", "satans", "skit", "skiten", "skiten",
    "skört", "kuk", "kukar", "fitta", "fittan", "knulla", "knullar", "knullade",
    "hora", "horan", "horor", "bög", "bögar", "as", "asen", "kärring",
    "rövhål", "röv", "röven", "arsel", "arslet", "piss", "pissa", "runka",
    "runkar", "slyna", "slynan", "subban", "subba", "mongo", "idiot", "idioter",
    "dö", "död", "döda", "dödar", "dödade", "dör", "dog", "mörda", "mördare",
    "mördad", "mördat", "sex", "sexet", "sexig", "porr", "naken", "naket",
    "droger", "drog", "knark", "sprit", "berusad", "full", "fyllo",
    "gud", "guds", "jesus", "kristus", "herregud", "gudskelov",
}


def download_words():
    print(f"Downloading frequency list from:\n  {SOURCE_URL}")
    req = urllib.request.Request(SOURCE_URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        text = resp.read().decode("utf-8", errors="replace")

    words = []
    seen = set()
    for line in text.splitlines():
        parts = line.split()
        if not parts:
            continue
        word = parts[0].strip().lower()

        if not VALID_WORD.match(word):
            continue
        if word in BLOCKLIST:
            continue
        # Skip lone single letters except real Swedish one-letter words.
        if len(word) == 1 and word not in ("i", "å"):
            continue
        if word in seen:
            continue

        seen.add(word)
        words.append(word)
        if len(words) >= TARGET_COUNT:
            break

    return words


def write_js(words):
    lines = []
    lines.append("// AUTO-GENERATED by download_common_swedish_words.py — DO NOT EDIT MANUALLY.")
    lines.append("//")
    lines.append("// The most common Swedish words, ordered from most to least frequent.")
    lines.append("// Source: hermitdave/FrequencyWords (OpenSubtitles 2018), profanity filtered.")
    lines.append("//")
    lines.append("// Used by the speed-reading minigame (SpeedReadingMode). An admin setting")
    lines.append("// (speedReading.wordCount) controls how many of these top words are in play.")
    lines.append("")
    lines.append(f"export const COMMON_SWEDISH_WORDS = [")

    # 8 words per line for readability.
    per_line = 8
    for i in range(0, len(words), per_line):
        chunk = words[i:i + per_line]
        quoted = ", ".join(f"'{w}'" for w in chunk)
        lines.append(f"    {quoted},")

    lines.append("];")
    lines.append("")
    lines.append("/**")
    lines.append(" * Get the top-N common words (N clamped to the list length).")
    lines.append(" * @param {number} count - How many of the most common words to include.")
    lines.append(" * @returns {string[]} The first `count` words, most common first.")
    lines.append(" */")
    lines.append("export function getTopCommonWords(count) {")
    lines.append("    const n = Math.max(1, Math.min(count || COMMON_SWEDISH_WORDS.length, COMMON_SWEDISH_WORDS.length));")
    lines.append("    return COMMON_SWEDISH_WORDS.slice(0, n);")
    lines.append("}")
    lines.append("")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    words = download_words()
    if len(words) < 100:
        print(f"ERROR: only got {len(words)} words, something went wrong.", file=sys.stderr)
        sys.exit(1)
    write_js(words)
    print(f"Wrote {len(words)} words to {OUTPUT_FILE}")
    print(f"First 20: {', '.join(words[:20])}")


if __name__ == "__main__":
    main()
