#!/usr/bin/env python3
"""
Fetch comprehensive Pokemon data from PokeAPI and generate pokemonData.js
Fetches types, stats, height, and weight for all Pokemon
"""

import requests
import json
import os
from pathlib import Path

# Build FILENAME_MAP from actual downloaded images
print("Scanning public/pokemon_images directory...")
FILENAME_MAP = {}
image_dir = Path("public/pokemon_images")

if image_dir.exists():
    for image_file in sorted(image_dir.glob("*.png")):
        # Extract Pokemon ID from filename (format: 001_bulbasaur.png)
        filename = image_file.name
        try:
            pokemon_id = int(filename.split('_')[0])
            FILENAME_MAP[pokemon_id] = filename
        except (ValueError, IndexError):
            print(f"Warning: Skipping malformed filename: {filename}")

max_pokemon = max(FILENAME_MAP.keys()) if FILENAME_MAP else 151
print(f"Found {len(FILENAME_MAP)} Pokemon images (highest ID: #{max_pokemon})")

print("\nFetching comprehensive Pokemon data from PokeAPI...")
print(f"This will fetch data for Pokemon #1-#{max_pokemon} (may take several minutes)\n")

pokemon_data = []

for pokemon_id in range(1, max_pokemon + 1):
    try:
        print(f"Fetching Pokemon #{pokemon_id}...", end=" ")

        # Fetch Pokemon data from API
        response = requests.get(f'https://pokeapi.co/api/v2/pokemon/{pokemon_id}')
        response.raise_for_status()
        data = response.json()

        # Extract type IDs
        types = []
        for type_data in data['types']:
            type_url = type_data['type']['url']
            type_id = int(type_url.rstrip('/').split('/')[-1])
            types.append(type_id)

        # Extract stats
        stats = {}
        stat_name_map = {
            'hp': 'hp',
            'attack': 'attack',
            'defense': 'defense',
            'special-attack': 'specialAttack',
            'special-defense': 'specialDefense',
            'speed': 'speed'
        }

        for stat_data in data['stats']:
            stat_name = stat_data['stat']['name']
            if stat_name in stat_name_map:
                stats[stat_name_map[stat_name]] = stat_data['base_stat']

        # Create Pokemon entry
        pokemon_entry = {
            'id': pokemon_id,
            'name': data['name'].capitalize(),
            'filename': FILENAME_MAP[pokemon_id],
            'types': types,
            'height': data['height'],
            'weight': data['weight'],
            'stats': stats
        }

        pokemon_data.append(pokemon_entry)
        print(f"✓ {pokemon_entry['name']}")

    except Exception as e:
        print(f"✗ Error: {e}")
        continue

print(f"\n✓ Successfully fetched data for {len(pokemon_data)} Pokemon")

# Generate JavaScript file
print("\nGenerating src/pokemonData.js...")

js_content = f"// All {len(pokemon_data)} Pokemon data (Generations 1-9)\n// Generated by fetch_pokemon_data.py - DO NOT EDIT MANUALLY\n"
js_content += "export const POKEMON_DATA = [\n"

for i, pokemon in enumerate(pokemon_data):
    # Format types array
    types_str = json.dumps(pokemon['types'])

    # Format stats object
    stats_str = json.dumps(pokemon['stats'], indent=4)
    stats_str = stats_str.replace('\n', '\n        ')  # Indent properly

    # Create Pokemon entry
    entry = f"    {{\n"
    entry += f"        id: {pokemon['id']},\n"
    entry += f"        name: \"{pokemon['name']}\",\n"
    entry += f"        filename: \"{pokemon['filename']}\",\n"
    entry += f"        types: {types_str},\n"
    entry += f"        height: {pokemon['height']},\n"
    entry += f"        weight: {pokemon['weight']},\n"
    entry += f"        stats: {stats_str}\n"
    entry += f"    }}"

    # Add comma if not last
    if i < len(pokemon_data) - 1:
        entry += ","

    entry += "\n"
    js_content += entry

js_content += "];\n"

# Write to file
with open('src/pokemonData.js', 'w') as f:
    f.write(js_content)

print("✓ Successfully generated src/pokemonData.js")
print(f"\nDone! Enhanced data for {len(pokemon_data)} Pokemon")
