#!/usr/bin/env python3
"""
Fetch comprehensive Pokemon data from PokeAPI and generate src/pokemonData.js.

For every Pokemon with an image in public/pokemon_images/ (run
download_pokemon_images.py first) this fetches types, stats, height and weight
from /pokemon/{id}, and whether it is legendary or mythical from
/pokemon-species/{id} (src/pokemonRarity.js puts those in the top rarity tier).

Requires: pip install requests
"""

import json
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import requests

API = 'https://pokeapi.co/api/v2'
WORKERS = 4  # be gentle with the public API

# Build FILENAME_MAP from actual downloaded images
print("Scanning public/pokemon_images directory...")
FILENAME_MAP = {}
image_dir = Path("public/pokemon_images")

if image_dir.exists():
    for image_file in sorted(image_dir.glob("*.png")):
        # Extract Pokemon ID from filename (format: 001_bulbasaur.png)
        filename = image_file.name
        try:
            pokemon_id = int(filename.split('_')[0])
            FILENAME_MAP[pokemon_id] = filename
        except (ValueError, IndexError):
            print(f"Warning: Skipping malformed filename: {filename}")

max_pokemon = max(FILENAME_MAP.keys()) if FILENAME_MAP else 151
print(f"Found {len(FILENAME_MAP)} Pokemon images (highest ID: #{max_pokemon})")

print("\nFetching comprehensive Pokemon data from PokeAPI...")
print(f"This will fetch data for Pokemon #1-#{max_pokemon} (may take several minutes)\n")

STAT_NAME_MAP = {
    'hp': 'hp',
    'attack': 'attack',
    'defense': 'defense',
    'special-attack': 'specialAttack',
    'special-defense': 'specialDefense',
    'speed': 'speed'
}

session = requests.Session()


def get_json(path):
    for attempt in range(3):
        try:
            response = session.get(f'{API}/{path}', timeout=20)
            response.raise_for_status()
            return response.json()
        except requests.RequestException as error:
            if attempt == 2:
                raise
            print(f"  retry {path}: {error}")
    return None


def fetch_pokemon(pokemon_id):
    if pokemon_id not in FILENAME_MAP:
        return None
    try:
        data = get_json(f'pokemon/{pokemon_id}')
        species = get_json(f'pokemon-species/{pokemon_id}')

        types = [int(t['type']['url'].rstrip('/').split('/')[-1]) for t in data['types']]
        stats = {
            STAT_NAME_MAP[s['stat']['name']]: s['base_stat']
            for s in data['stats'] if s['stat']['name'] in STAT_NAME_MAP
        }
        entry = {
            'id': pokemon_id,
            'name': data['name'].capitalize(),
            'filename': FILENAME_MAP[pokemon_id],
            'types': types,
            'height': data['height'],
            'weight': data['weight'],
            'stats': stats,
            'legendary': bool(species.get('is_legendary') or species.get('is_mythical'))
        }
        print(f"✓ #{pokemon_id} {entry['name']}{' (legendary)' if entry['legendary'] else ''}")
        return entry
    except Exception as error:  # noqa: BLE001
        print(f"✗ #{pokemon_id}: {error}")
        return None


with ThreadPoolExecutor(max_workers=WORKERS) as pool:
    results = list(pool.map(fetch_pokemon, range(1, max_pokemon + 1)))

pokemon_data = [entry for entry in results if entry]
missing = [pid for pid in range(1, max_pokemon + 1) if pid in FILENAME_MAP and not results[pid - 1]]
print(f"\n✓ Successfully fetched data for {len(pokemon_data)} Pokemon")
if missing:
    print(f"✗ Failed for {len(missing)}: {missing[:20]} ... not writing the file", file=sys.stderr)
    sys.exit(1)

# Generate JavaScript file
print("\nGenerating src/pokemonData.js...")

js_content = f"// All {len(pokemon_data)} Pokemon data (Generations 1-9)\n// Generated by fetch_pokemon_data.py - DO NOT EDIT MANUALLY\n\n"
js_content += "export const POKEMON_DATA = [\n"

for i, pokemon in enumerate(pokemon_data):
    types_str = json.dumps(pokemon['types'])
    stats_str = json.dumps(pokemon['stats'], indent=4).replace('\n', '\n        ')

    entry = "    {\n"
    entry += f"        id: {pokemon['id']},\n"
    entry += f"        name: \"{pokemon['name']}\",\n"
    entry += f"        filename: \"{pokemon['filename']}\",\n"
    entry += f"        types: {types_str},\n"
    entry += f"        height: {pokemon['height']},\n"
    entry += f"        weight: {pokemon['weight']},\n"
    if pokemon['legendary']:
        entry += "        legendary: true,\n"
    entry += f"        stats: {stats_str}\n"
    entry += "    }"
    if i < len(pokemon_data) - 1:
        entry += ","
    js_content += entry + "\n"

js_content += "];\n"

with open('src/pokemonData.js', 'w') as f:
    f.write(js_content)

print("✓ Successfully generated src/pokemonData.js")
print(f"\nDone! Data for {len(pokemon_data)} Pokemon, {sum(p['legendary'] for p in pokemon_data)} legendary/mythical")
