#!/usr/bin/env python3
"""
Build the word list for the spelling minigame, and the audio to go with it.

Source: src/commonSwedishWords.js (top 1000 Swedish words by frequency).
We take the top TOP_N and drop four groups that make the game teach the wrong
thing - see the blocklists below for the reasoning.

Outputs, both from this one script so the list and the audio can never drift:
  - src/spellingWords.js       the word list the game imports
  - public/word_audio/*.mp3    one file per word (the game never shows the word,
                               the child only hears it)

Usage:
    python3 generate_spelling_words.py            # skip words that already have audio
    python3 generate_spelling_words.py --force    # regenerate every mp3
    python3 generate_spelling_words.py --list-only  # write the JS, no audio
"""

import asyncio
import os
import re
import subprocess
import sys

import edge_tts

# Same Swedish voice as the letter, number and math audio, so a word and the
# letters spelled back to the child are the same speaker.
VOICE = "sv-SE-MattiasNeural"

SOURCE_JS = "src/commonSwedishWords.js"
OUTPUT_JS = "src/spellingWords.js"
AUDIO_DIR = "public/word_audio"

# How far down the frequency list to go.
TOP_N = 500

# --- Blocklists -------------------------------------------------------------
# 1. Not real Swedish words: subtitle residue - names, abbreviations, English.
#    'lnte' is an OCR error for 'Inte' (capital I read as lowercase L); it sits
#    at rank 857 so it is outside TOP_N today, kept here in case the pool grows.
JUNK = {
    'mr', 'dr', 'mrs', 'ms', 'sir', 'herr',
    'the', 'new', 'york', 'ok', 'oh', 'miss', 'la', 'pa',
    'lnte',
    'john', 'jack', 'charlie', 'sam', 'david', 'frank', 'george', 'mike',
    'michael', 'max', 'peter', 'dan', 'james', 'mark', 'paul', 'henry',
    'alex', 'tom',
}

# 2. Spoken forms whose correct written form is something else. These are the
#    worst offenders: the child would spell them "right" per the game and wrong
#    per the language. nat -> nagot, dom -> de/dem, stan -> staden.
SPOKEN_FORMS = {
    'okej', 'nåt', 'nån', 'sån', 'sånt', 'såna', 'dom', 'va', 'vadå',
    'jaså', 'jaha', 'tja', 'åh', 'oj', 'hallå', 'jo', 'nä', 'stan',
}

# 3. Spelling and pronunciation disagree so badly the word cannot be sounded
#    out at all: och="å", är="e", jag="ja", mig/dig/sig="mej/dej/sej",
#    säger="säjer", sagt="sakt", dag="da", morgon="morron".
#    High-value words, but they are learned as whole-word shapes rather than by
#    listening and spelling, which is exactly what this game does.
NOT_PHONETIC = {
    'och', 'är', 'jag', 'det', 'de', 'dem', 'mig', 'dig', 'sig',
    'mycket', 'vad', 'sedan', 'sen', 'någon', 'något', 'några',
    'dag', 'dagen', 'dagar', 'dags', 'morgon',
    'säger', 'säga', 'sagt', 'värld', 'världen', 'ja', 'nej',
}

# 4. Silent opening consonant - the child cannot hear the first letter at all.
SILENT_START = re.compile(r'^(hj|lj|dj|gj|sj|stj|skj|tj|kj)')


def read_source_words():
    """Pull the quoted words out of the generated commonSwedishWords.js"""
    with open(SOURCE_JS, encoding='utf-8') as f:
        source = f.read()

    # The array literal holds single-quoted lowercase words, 8 per line
    start = source.index('COMMON_SWEDISH_WORDS')
    end = source.index('];', start)
    words = re.findall(r"'([a-zåäö]+)'", source[start:end])

    if not words:
        raise SystemExit(f"No words found in {SOURCE_JS}")
    return words


def filter_words(words):
    """Apply the four blocklists, keeping frequency order"""
    kept, dropped = [], {'junk': [], 'spoken': [], 'not_phonetic': [], 'silent': []}

    for word in words[:TOP_N]:
        if word in JUNK:
            dropped['junk'].append(word)
        elif word in SPOKEN_FORMS:
            dropped['spoken'].append(word)
        elif word in NOT_PHONETIC:
            dropped['not_phonetic'].append(word)
        elif SILENT_START.match(word):
            dropped['silent'].append(word)
        else:
            kept.append(word)

    return kept, dropped


def write_js(words):
    """Write src/spellingWords.js in the same shape as commonSwedishWords.js"""
    lines = []
    for i in range(0, len(words), 8):
        chunk = ", ".join(f"'{w}'" for w in words[i:i + 8])
        lines.append(f"    {chunk},")
    array_body = "\n".join(lines).rstrip(",")

    content = f"""// AUTO-GENERATED by generate_spelling_words.py - DO NOT EDIT MANUALLY
//
// The word pool for the spelling minigame: the {len(words)} most common Swedish
// words from commonSwedishWords.js (top {TOP_N} by frequency), minus words that
// would teach the wrong thing - subtitle junk, spoken forms whose written form
// differs, words that cannot be sounded out, and silent opening consonants.
// See the blocklists in generate_spelling_words.py for the reasoning.
//
// Every word here has a matching public/word_audio/<word>.mp3.

export const SPELLING_WORDS = [
{array_body}
];

// The first `count` words, i.e. the most common ones. Lets the pool be narrowed
// from the admin panel without regenerating any audio.
export function getSpellingWords(count) {{
    const n = Math.max(1, Math.min(count || SPELLING_WORDS.length, SPELLING_WORDS.length));
    return SPELLING_WORDS.slice(0, n);
}}
"""

    with open(OUTPUT_JS, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"✓ Wrote {OUTPUT_JS} ({len(words)} words)")


def trim_audio_file(filepath):
    """Edge-TTS pads ~240ms at the start and ~930ms at the end - strip both"""
    temp_file = filepath + ".trimmed.mp3"
    cmd = [
        'ffmpeg', '-i', filepath,
        '-af', 'silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.05:'
               'stop_periods=-1:stop_threshold=-50dB:stop_silence=0.05',
        '-y', temp_file
    ]
    try:
        subprocess.run(cmd, capture_output=True, check=True)
        os.replace(temp_file, filepath)
        return True
    except subprocess.CalledProcessError as e:
        print(f"✗ Failed to trim {filepath}: {e}")
        if os.path.exists(temp_file):
            os.remove(temp_file)
        return False


async def generate_audio(words, force):
    """One mp3 per word. Existing files are left alone unless --force."""
    os.makedirs(AUDIO_DIR, exist_ok=True)

    todo = []
    for word in words:
        filepath = f"{AUDIO_DIR}/{word}.mp3"
        if force or not os.path.exists(filepath):
            todo.append((word, filepath))

    skipped = len(words) - len(todo)
    if skipped:
        print(f"\nSkipping {skipped} word(s) that already have audio (use --force to redo)")
    if not todo:
        print("Nothing to generate")
        return

    print(f"Generating {len(todo)} audio file(s) with {VOICE}...\n")

    failures = []
    for i, (word, filepath) in enumerate(todo, 1):
        try:
            tts = edge_tts.Communicate(word, VOICE)
            await tts.save(filepath)
            trim_audio_file(filepath)
            print(f"  [{i}/{len(todo)}] ✓ {word}")
        except Exception as e:
            print(f"  [{i}/{len(todo)}] ✗ {word}: {e}")
            failures.append(word)

    print(f"\n✓ Generated {len(todo) - len(failures)}/{len(todo)} files")
    if failures:
        print(f"✗ Failed: {', '.join(failures)}")


async def main():
    force = '--force' in sys.argv
    list_only = '--list-only' in sys.argv

    source_words = read_source_words()
    print(f"Read {len(source_words)} words from {SOURCE_JS}")

    kept, dropped = filter_words(source_words)

    print(f"\nTop {TOP_N} filtered down to {len(kept)} words:")
    for label, words in dropped.items():
        if words:
            print(f"  - dropped {len(words):>2} ({label}): {', '.join(words)}")

    write_js(kept)

    if not list_only:
        await generate_audio(kept, force)


if __name__ == "__main__":
    asyncio.run(main())
