#!/usr/bin/env python3
"""
Trim silence from clock audio files generated by Edge-TTS

Edge-TTS adds ~240ms silence at start and ~930ms at end.
This script removes that silence for cleaner audio playback.
"""

import subprocess
import os
from pathlib import Path

def trim_audio_file(filepath):
    """Trim silence from audio file using ffmpeg"""
    temp = str(filepath) + ".tmp.mp3"

    print(f"Trimming: {filepath.name}")

    try:
        subprocess.run([
            'ffmpeg', '-i', str(filepath),
            '-af', 'silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.05:stop_periods=-1:stop_threshold=-50dB:stop_silence=0.05',
            '-y', temp
        ], capture_output=True, check=True)

        # Replace original with trimmed version
        os.replace(temp, filepath)
        print(f"  ✓ Trimmed: {filepath.name}")

    except subprocess.CalledProcessError as e:
        print(f"  ✗ Error trimming {filepath.name}: {e}")
        if os.path.exists(temp):
            os.remove(temp)
    except FileNotFoundError:
        print("Error: ffmpeg not found. Install with: brew install ffmpeg")
        exit(1)

def main():
    audio_dir = Path('public/clock_audio')

    if not audio_dir.exists():
        print(f"Error: Directory not found: {audio_dir}")
        print("Run generate_clock_audio.py first")
        exit(1)

    audio_files = list(audio_dir.glob('*.mp3'))

    if not audio_files:
        print(f"No MP3 files found in {audio_dir}")
        exit(1)

    print(f"Found {len(audio_files)} audio files\n")

    for filepath in sorted(audio_files):
        trim_audio_file(filepath)

    print(f"\n✓ Trimmed {len(audio_files)} files in {audio_dir}")

if __name__ == "__main__":
    main()
