// All 151 Gen 1 Pokemon data
// Generated by fetch_pokemon_data.py - DO NOT EDIT MANUALLY
export const POKEMON_DATA = [
    {
        id: 1,
        name: "Bulbasaur",
        filename: "001_bulbasaur.png",
        types: [12, 4],
        height: 7,
        weight: 69,
        stats: {
            "hp": 45,
            "attack": 49,
            "defense": 49,
            "specialAttack": 65,
            "specialDefense": 65,
            "speed": 45
        }
    },
    {
        id: 2,
        name: "Ivysaur",
        filename: "002_ivysaur.png",
        types: [12, 4],
        height: 10,
        weight: 130,
        stats: {
            "hp": 60,
            "attack": 62,
            "defense": 63,
            "specialAttack": 80,
            "specialDefense": 80,
            "speed": 60
        }
    },
    {
        id: 3,
        name: "Venusaur",
        filename: "003_venusaur.png",
        types: [12, 4],
        height: 20,
        weight: 1000,
        stats: {
            "hp": 80,
            "attack": 82,
            "defense": 83,
            "specialAttack": 100,
            "specialDefense": 100,
            "speed": 80
        }
    },
    {
        id: 4,
        name: "Charmander",
        filename: "004_charmander.png",
        types: [10],
        height: 6,
        weight: 85,
        stats: {
            "hp": 39,
            "attack": 52,
            "defense": 43,
            "specialAttack": 60,
            "specialDefense": 50,
            "speed": 65
        }
    },
    {
        id: 5,
        name: "Charmeleon",
        filename: "005_charmeleon.png",
        types: [10],
        height: 11,
        weight: 190,
        stats: {
            "hp": 58,
            "attack": 64,
            "defense": 58,
            "specialAttack": 80,
            "specialDefense": 65,
            "speed": 80
        }
    },
    {
        id: 6,
        name: "Charizard",
        filename: "006_charizard.png",
        types: [10, 3],
        height: 17,
        weight: 905,
        stats: {
            "hp": 78,
            "attack": 84,
            "defense": 78,
            "specialAttack": 109,
            "specialDefense": 85,
            "speed": 100
        }
    },
    {
        id: 7,
        name: "Squirtle",
        filename: "007_squirtle.png",
        types: [11],
        height: 5,
        weight: 90,
        stats: {
            "hp": 44,
            "attack": 48,
            "defense": 65,
            "specialAttack": 50,
            "specialDefense": 64,
            "speed": 43
        }
    },
    {
        id: 8,
        name: "Wartortle",
        filename: "008_wartortle.png",
        types: [11],
        height: 10,
        weight: 225,
        stats: {
            "hp": 59,
            "attack": 63,
            "defense": 80,
            "specialAttack": 65,
            "specialDefense": 80,
            "speed": 58
        }
    },
    {
        id: 9,
        name: "Blastoise",
        filename: "009_blastoise.png",
        types: [11],
        height: 16,
        weight: 855,
        stats: {
            "hp": 79,
            "attack": 83,
            "defense": 100,
            "specialAttack": 85,
            "specialDefense": 105,
            "speed": 78
        }
    },
    {
        id: 10,
        name: "Caterpie",
        filename: "010_caterpie.png",
        types: [7],
        height: 3,
        weight: 29,
        stats: {
            "hp": 45,
            "attack": 30,
            "defense": 35,
            "specialAttack": 20,
            "specialDefense": 20,
            "speed": 45
        }
    },
    {
        id: 11,
        name: "Metapod",
        filename: "011_metapod.png",
        types: [7],
        height: 7,
        weight: 99,
        stats: {
            "hp": 50,
            "attack": 20,
            "defense": 55,
            "specialAttack": 25,
            "specialDefense": 25,
            "speed": 30
        }
    },
    {
        id: 12,
        name: "Butterfree",
        filename: "012_butterfree.png",
        types: [7, 3],
        height: 11,
        weight: 320,
        stats: {
            "hp": 60,
            "attack": 45,
            "defense": 50,
            "specialAttack": 90,
            "specialDefense": 80,
            "speed": 70
        }
    },
    {
        id: 13,
        name: "Weedle",
        filename: "013_weedle.png",
        types: [7, 4],
        height: 3,
        weight: 32,
        stats: {
            "hp": 40,
            "attack": 35,
            "defense": 30,
            "specialAttack": 20,
            "specialDefense": 20,
            "speed": 50
        }
    },
    {
        id: 14,
        name: "Kakuna",
        filename: "014_kakuna.png",
        types: [7, 4],
        height: 6,
        weight: 100,
        stats: {
            "hp": 45,
            "attack": 25,
            "defense": 50,
            "specialAttack": 25,
            "specialDefense": 25,
            "speed": 35
        }
    },
    {
        id: 15,
        name: "Beedrill",
        filename: "015_beedrill.png",
        types: [7, 4],
        height: 10,
        weight: 295,
        stats: {
            "hp": 65,
            "attack": 90,
            "defense": 40,
            "specialAttack": 45,
            "specialDefense": 80,
            "speed": 75
        }
    },
    {
        id: 16,
        name: "Pidgey",
        filename: "016_pidgey.png",
        types: [1, 3],
        height: 3,
        weight: 18,
        stats: {
            "hp": 40,
            "attack": 45,
            "defense": 40,
            "specialAttack": 35,
            "specialDefense": 35,
            "speed": 56
        }
    },
    {
        id: 17,
        name: "Pidgeotto",
        filename: "017_pidgeotto.png",
        types: [1, 3],
        height: 11,
        weight: 300,
        stats: {
            "hp": 63,
            "attack": 60,
            "defense": 55,
            "specialAttack": 50,
            "specialDefense": 50,
            "speed": 71
        }
    },
    {
        id: 18,
        name: "Pidgeot",
        filename: "018_pidgeot.png",
        types: [1, 3],
        height: 15,
        weight: 395,
        stats: {
            "hp": 83,
            "attack": 80,
            "defense": 75,
            "specialAttack": 70,
            "specialDefense": 70,
            "speed": 101
        }
    },
    {
        id: 19,
        name: "Rattata",
        filename: "019_rattata.png",
        types: [1],
        height: 3,
        weight: 35,
        stats: {
            "hp": 30,
            "attack": 56,
            "defense": 35,
            "specialAttack": 25,
            "specialDefense": 35,
            "speed": 72
        }
    },
    {
        id: 20,
        name: "Raticate",
        filename: "020_raticate.png",
        types: [1],
        height: 7,
        weight: 185,
        stats: {
            "hp": 55,
            "attack": 81,
            "defense": 60,
            "specialAttack": 50,
            "specialDefense": 70,
            "speed": 97
        }
    },
    {
        id: 21,
        name: "Spearow",
        filename: "021_spearow.png",
        types: [1, 3],
        height: 3,
        weight: 20,
        stats: {
            "hp": 40,
            "attack": 60,
            "defense": 30,
            "specialAttack": 31,
            "specialDefense": 31,
            "speed": 70
        }
    },
    {
        id: 22,
        name: "Fearow",
        filename: "022_fearow.png",
        types: [1, 3],
        height: 12,
        weight: 380,
        stats: {
            "hp": 65,
            "attack": 90,
            "defense": 65,
            "specialAttack": 61,
            "specialDefense": 61,
            "speed": 100
        }
    },
    {
        id: 23,
        name: "Ekans",
        filename: "023_ekans.png",
        types: [4],
        height: 20,
        weight: 69,
        stats: {
            "hp": 35,
            "attack": 60,
            "defense": 44,
            "specialAttack": 40,
            "specialDefense": 54,
            "speed": 55
        }
    },
    {
        id: 24,
        name: "Arbok",
        filename: "024_arbok.png",
        types: [4],
        height: 35,
        weight: 650,
        stats: {
            "hp": 60,
            "attack": 95,
            "defense": 69,
            "specialAttack": 65,
            "specialDefense": 79,
            "speed": 80
        }
    },
    {
        id: 25,
        name: "Pikachu",
        filename: "025_pikachu.png",
        types: [13],
        height: 4,
        weight: 60,
        stats: {
            "hp": 35,
            "attack": 55,
            "defense": 40,
            "specialAttack": 50,
            "specialDefense": 50,
            "speed": 90
        }
    },
    {
        id: 26,
        name: "Raichu",
        filename: "026_raichu.png",
        types: [13],
        height: 8,
        weight: 300,
        stats: {
            "hp": 60,
            "attack": 90,
            "defense": 55,
            "specialAttack": 90,
            "specialDefense": 80,
            "speed": 110
        }
    },
    {
        id: 27,
        name: "Sandshrew",
        filename: "027_sandshrew.png",
        types: [5],
        height: 6,
        weight: 120,
        stats: {
            "hp": 50,
            "attack": 75,
            "defense": 85,
            "specialAttack": 20,
            "specialDefense": 30,
            "speed": 40
        }
    },
    {
        id: 28,
        name: "Sandslash",
        filename: "028_sandslash.png",
        types: [5],
        height: 10,
        weight: 295,
        stats: {
            "hp": 75,
            "attack": 100,
            "defense": 110,
            "specialAttack": 45,
            "specialDefense": 55,
            "speed": 65
        }
    },
    {
        id: 29,
        name: "Nidoran-f",
        filename: "029_nidoran-f.png",
        types: [4],
        height: 4,
        weight: 70,
        stats: {
            "hp": 55,
            "attack": 47,
            "defense": 52,
            "specialAttack": 40,
            "specialDefense": 40,
            "speed": 41
        }
    },
    {
        id: 30,
        name: "Nidorina",
        filename: "030_nidorina.png",
        types: [4],
        height: 8,
        weight: 200,
        stats: {
            "hp": 70,
            "attack": 62,
            "defense": 67,
            "specialAttack": 55,
            "specialDefense": 55,
            "speed": 56
        }
    },
    {
        id: 31,
        name: "Nidoqueen",
        filename: "031_nidoqueen.png",
        types: [4, 5],
        height: 13,
        weight: 600,
        stats: {
            "hp": 90,
            "attack": 92,
            "defense": 87,
            "specialAttack": 75,
            "specialDefense": 85,
            "speed": 76
        }
    },
    {
        id: 32,
        name: "Nidoran-m",
        filename: "032_nidoran-m.png",
        types: [4],
        height: 5,
        weight: 90,
        stats: {
            "hp": 46,
            "attack": 57,
            "defense": 40,
            "specialAttack": 40,
            "specialDefense": 40,
            "speed": 50
        }
    },
    {
        id: 33,
        name: "Nidorino",
        filename: "033_nidorino.png",
        types: [4],
        height: 9,
        weight: 195,
        stats: {
            "hp": 61,
            "attack": 72,
            "defense": 57,
            "specialAttack": 55,
            "specialDefense": 55,
            "speed": 65
        }
    },
    {
        id: 34,
        name: "Nidoking",
        filename: "034_nidoking.png",
        types: [4, 5],
        height: 14,
        weight: 620,
        stats: {
            "hp": 81,
            "attack": 102,
            "defense": 77,
            "specialAttack": 85,
            "specialDefense": 75,
            "speed": 85
        }
    },
    {
        id: 35,
        name: "Clefairy",
        filename: "035_clefairy.png",
        types: [18],
        height: 6,
        weight: 75,
        stats: {
            "hp": 70,
            "attack": 45,
            "defense": 48,
            "specialAttack": 60,
            "specialDefense": 65,
            "speed": 35
        }
    },
    {
        id: 36,
        name: "Clefable",
        filename: "036_clefable.png",
        types: [18],
        height: 13,
        weight: 400,
        stats: {
            "hp": 95,
            "attack": 70,
            "defense": 73,
            "specialAttack": 95,
            "specialDefense": 90,
            "speed": 60
        }
    },
    {
        id: 37,
        name: "Vulpix",
        filename: "037_vulpix.png",
        types: [10],
        height: 6,
        weight: 99,
        stats: {
            "hp": 38,
            "attack": 41,
            "defense": 40,
            "specialAttack": 50,
            "specialDefense": 65,
            "speed": 65
        }
    },
    {
        id: 38,
        name: "Ninetales",
        filename: "038_ninetales.png",
        types: [10],
        height: 11,
        weight: 199,
        stats: {
            "hp": 73,
            "attack": 76,
            "defense": 75,
            "specialAttack": 81,
            "specialDefense": 100,
            "speed": 100
        }
    },
    {
        id: 39,
        name: "Jigglypuff",
        filename: "039_jigglypuff.png",
        types: [1, 18],
        height: 5,
        weight: 55,
        stats: {
            "hp": 115,
            "attack": 45,
            "defense": 20,
            "specialAttack": 45,
            "specialDefense": 25,
            "speed": 20
        }
    },
    {
        id: 40,
        name: "Wigglytuff",
        filename: "040_wigglytuff.png",
        types: [1, 18],
        height: 10,
        weight: 120,
        stats: {
            "hp": 140,
            "attack": 70,
            "defense": 45,
            "specialAttack": 85,
            "specialDefense": 50,
            "speed": 45
        }
    },
    {
        id: 41,
        name: "Zubat",
        filename: "041_zubat.png",
        types: [4, 3],
        height: 8,
        weight: 75,
        stats: {
            "hp": 40,
            "attack": 45,
            "defense": 35,
            "specialAttack": 30,
            "specialDefense": 40,
            "speed": 55
        }
    },
    {
        id: 42,
        name: "Golbat",
        filename: "042_golbat.png",
        types: [4, 3],
        height: 16,
        weight: 550,
        stats: {
            "hp": 75,
            "attack": 80,
            "defense": 70,
            "specialAttack": 65,
            "specialDefense": 75,
            "speed": 90
        }
    },
    {
        id: 43,
        name: "Oddish",
        filename: "043_oddish.png",
        types: [12, 4],
        height: 5,
        weight: 54,
        stats: {
            "hp": 45,
            "attack": 50,
            "defense": 55,
            "specialAttack": 75,
            "specialDefense": 65,
            "speed": 30
        }
    },
    {
        id: 44,
        name: "Gloom",
        filename: "044_gloom.png",
        types: [12, 4],
        height: 8,
        weight: 86,
        stats: {
            "hp": 60,
            "attack": 65,
            "defense": 70,
            "specialAttack": 85,
            "specialDefense": 75,
            "speed": 40
        }
    },
    {
        id: 45,
        name: "Vileplume",
        filename: "045_vileplume.png",
        types: [12, 4],
        height: 12,
        weight: 186,
        stats: {
            "hp": 75,
            "attack": 80,
            "defense": 85,
            "specialAttack": 110,
            "specialDefense": 90,
            "speed": 50
        }
    },
    {
        id: 46,
        name: "Paras",
        filename: "046_paras.png",
        types: [7, 12],
        height: 3,
        weight: 54,
        stats: {
            "hp": 35,
            "attack": 70,
            "defense": 55,
            "specialAttack": 45,
            "specialDefense": 55,
            "speed": 25
        }
    },
    {
        id: 47,
        name: "Parasect",
        filename: "047_parasect.png",
        types: [7, 12],
        height: 10,
        weight: 295,
        stats: {
            "hp": 60,
            "attack": 95,
            "defense": 80,
            "specialAttack": 60,
            "specialDefense": 80,
            "speed": 30
        }
    },
    {
        id: 48,
        name: "Venonat",
        filename: "048_venonat.png",
        types: [7, 4],
        height: 10,
        weight: 300,
        stats: {
            "hp": 60,
            "attack": 55,
            "defense": 50,
            "specialAttack": 40,
            "specialDefense": 55,
            "speed": 45
        }
    },
    {
        id: 49,
        name: "Venomoth",
        filename: "049_venomoth.png",
        types: [7, 4],
        height: 15,
        weight: 125,
        stats: {
            "hp": 70,
            "attack": 65,
            "defense": 60,
            "specialAttack": 90,
            "specialDefense": 75,
            "speed": 90
        }
    },
    {
        id: 50,
        name: "Diglett",
        filename: "050_diglett.png",
        types: [5],
        height: 2,
        weight: 8,
        stats: {
            "hp": 10,
            "attack": 55,
            "defense": 25,
            "specialAttack": 35,
            "specialDefense": 45,
            "speed": 95
        }
    },
    {
        id: 51,
        name: "Dugtrio",
        filename: "051_dugtrio.png",
        types: [5],
        height: 7,
        weight: 333,
        stats: {
            "hp": 35,
            "attack": 100,
            "defense": 50,
            "specialAttack": 50,
            "specialDefense": 70,
            "speed": 120
        }
    },
    {
        id: 52,
        name: "Meowth",
        filename: "052_meowth.png",
        types: [1],
        height: 4,
        weight: 42,
        stats: {
            "hp": 40,
            "attack": 45,
            "defense": 35,
            "specialAttack": 40,
            "specialDefense": 40,
            "speed": 90
        }
    },
    {
        id: 53,
        name: "Persian",
        filename: "053_persian.png",
        types: [1],
        height: 10,
        weight: 320,
        stats: {
            "hp": 65,
            "attack": 70,
            "defense": 60,
            "specialAttack": 65,
            "specialDefense": 65,
            "speed": 115
        }
    },
    {
        id: 54,
        name: "Psyduck",
        filename: "054_psyduck.png",
        types: [11],
        height: 8,
        weight: 196,
        stats: {
            "hp": 50,
            "attack": 52,
            "defense": 48,
            "specialAttack": 65,
            "specialDefense": 50,
            "speed": 55
        }
    },
    {
        id: 55,
        name: "Golduck",
        filename: "055_golduck.png",
        types: [11],
        height: 17,
        weight: 766,
        stats: {
            "hp": 80,
            "attack": 82,
            "defense": 78,
            "specialAttack": 95,
            "specialDefense": 80,
            "speed": 85
        }
    },
    {
        id: 56,
        name: "Mankey",
        filename: "056_mankey.png",
        types: [2],
        height: 5,
        weight: 280,
        stats: {
            "hp": 40,
            "attack": 80,
            "defense": 35,
            "specialAttack": 35,
            "specialDefense": 45,
            "speed": 70
        }
    },
    {
        id: 57,
        name: "Primeape",
        filename: "057_primeape.png",
        types: [2],
        height: 10,
        weight: 320,
        stats: {
            "hp": 65,
            "attack": 105,
            "defense": 60,
            "specialAttack": 60,
            "specialDefense": 70,
            "speed": 95
        }
    },
    {
        id: 58,
        name: "Growlithe",
        filename: "058_growlithe.png",
        types: [10],
        height: 7,
        weight: 190,
        stats: {
            "hp": 55,
            "attack": 70,
            "defense": 45,
            "specialAttack": 70,
            "specialDefense": 50,
            "speed": 60
        }
    },
    {
        id: 59,
        name: "Arcanine",
        filename: "059_arcanine.png",
        types: [10],
        height: 19,
        weight: 1550,
        stats: {
            "hp": 90,
            "attack": 110,
            "defense": 80,
            "specialAttack": 100,
            "specialDefense": 80,
            "speed": 95
        }
    },
    {
        id: 60,
        name: "Poliwag",
        filename: "060_poliwag.png",
        types: [11],
        height: 6,
        weight: 124,
        stats: {
            "hp": 40,
            "attack": 50,
            "defense": 40,
            "specialAttack": 40,
            "specialDefense": 40,
            "speed": 90
        }
    },
    {
        id: 61,
        name: "Poliwhirl",
        filename: "061_poliwhirl.png",
        types: [11],
        height: 10,
        weight: 200,
        stats: {
            "hp": 65,
            "attack": 65,
            "defense": 65,
            "specialAttack": 50,
            "specialDefense": 50,
            "speed": 90
        }
    },
    {
        id: 62,
        name: "Poliwrath",
        filename: "062_poliwrath.png",
        types: [11, 2],
        height: 13,
        weight: 540,
        stats: {
            "hp": 90,
            "attack": 95,
            "defense": 95,
            "specialAttack": 70,
            "specialDefense": 90,
            "speed": 70
        }
    },
    {
        id: 63,
        name: "Abra",
        filename: "063_abra.png",
        types: [14],
        height: 9,
        weight: 195,
        stats: {
            "hp": 25,
            "attack": 20,
            "defense": 15,
            "specialAttack": 105,
            "specialDefense": 55,
            "speed": 90
        }
    },
    {
        id: 64,
        name: "Kadabra",
        filename: "064_kadabra.png",
        types: [14],
        height: 13,
        weight: 565,
        stats: {
            "hp": 40,
            "attack": 35,
            "defense": 30,
            "specialAttack": 120,
            "specialDefense": 70,
            "speed": 105
        }
    },
    {
        id: 65,
        name: "Alakazam",
        filename: "065_alakazam.png",
        types: [14],
        height: 15,
        weight: 480,
        stats: {
            "hp": 55,
            "attack": 50,
            "defense": 45,
            "specialAttack": 135,
            "specialDefense": 95,
            "speed": 120
        }
    },
    {
        id: 66,
        name: "Machop",
        filename: "066_machop.png",
        types: [2],
        height: 8,
        weight: 195,
        stats: {
            "hp": 70,
            "attack": 80,
            "defense": 50,
            "specialAttack": 35,
            "specialDefense": 35,
            "speed": 35
        }
    },
    {
        id: 67,
        name: "Machoke",
        filename: "067_machoke.png",
        types: [2],
        height: 15,
        weight: 705,
        stats: {
            "hp": 80,
            "attack": 100,
            "defense": 70,
            "specialAttack": 50,
            "specialDefense": 60,
            "speed": 45
        }
    },
    {
        id: 68,
        name: "Machamp",
        filename: "068_machamp.png",
        types: [2],
        height: 16,
        weight: 1300,
        stats: {
            "hp": 90,
            "attack": 130,
            "defense": 80,
            "specialAttack": 65,
            "specialDefense": 85,
            "speed": 55
        }
    },
    {
        id: 69,
        name: "Bellsprout",
        filename: "069_bellsprout.png",
        types: [12, 4],
        height: 7,
        weight: 40,
        stats: {
            "hp": 50,
            "attack": 75,
            "defense": 35,
            "specialAttack": 70,
            "specialDefense": 30,
            "speed": 40
        }
    },
    {
        id: 70,
        name: "Weepinbell",
        filename: "070_weepinbell.png",
        types: [12, 4],
        height: 10,
        weight: 64,
        stats: {
            "hp": 65,
            "attack": 90,
            "defense": 50,
            "specialAttack": 85,
            "specialDefense": 45,
            "speed": 55
        }
    },
    {
        id: 71,
        name: "Victreebel",
        filename: "071_victreebel.png",
        types: [12, 4],
        height: 17,
        weight: 155,
        stats: {
            "hp": 80,
            "attack": 105,
            "defense": 65,
            "specialAttack": 100,
            "specialDefense": 70,
            "speed": 70
        }
    },
    {
        id: 72,
        name: "Tentacool",
        filename: "072_tentacool.png",
        types: [11, 4],
        height: 9,
        weight: 455,
        stats: {
            "hp": 40,
            "attack": 40,
            "defense": 35,
            "specialAttack": 50,
            "specialDefense": 100,
            "speed": 70
        }
    },
    {
        id: 73,
        name: "Tentacruel",
        filename: "073_tentacruel.png",
        types: [11, 4],
        height: 16,
        weight: 550,
        stats: {
            "hp": 80,
            "attack": 70,
            "defense": 65,
            "specialAttack": 80,
            "specialDefense": 120,
            "speed": 100
        }
    },
    {
        id: 74,
        name: "Geodude",
        filename: "074_geodude.png",
        types: [6, 5],
        height: 4,
        weight: 200,
        stats: {
            "hp": 40,
            "attack": 80,
            "defense": 100,
            "specialAttack": 30,
            "specialDefense": 30,
            "speed": 20
        }
    },
    {
        id: 75,
        name: "Graveler",
        filename: "075_graveler.png",
        types: [6, 5],
        height: 10,
        weight: 1050,
        stats: {
            "hp": 55,
            "attack": 95,
            "defense": 115,
            "specialAttack": 45,
            "specialDefense": 45,
            "speed": 35
        }
    },
    {
        id: 76,
        name: "Golem",
        filename: "076_golem.png",
        types: [6, 5],
        height: 14,
        weight: 3000,
        stats: {
            "hp": 80,
            "attack": 120,
            "defense": 130,
            "specialAttack": 55,
            "specialDefense": 65,
            "speed": 45
        }
    },
    {
        id: 77,
        name: "Ponyta",
        filename: "077_ponyta.png",
        types: [10],
        height: 10,
        weight: 300,
        stats: {
            "hp": 50,
            "attack": 85,
            "defense": 55,
            "specialAttack": 65,
            "specialDefense": 65,
            "speed": 90
        }
    },
    {
        id: 78,
        name: "Rapidash",
        filename: "078_rapidash.png",
        types: [10],
        height: 17,
        weight: 950,
        stats: {
            "hp": 65,
            "attack": 100,
            "defense": 70,
            "specialAttack": 80,
            "specialDefense": 80,
            "speed": 105
        }
    },
    {
        id: 79,
        name: "Slowpoke",
        filename: "079_slowpoke.png",
        types: [11, 14],
        height: 12,
        weight: 360,
        stats: {
            "hp": 90,
            "attack": 65,
            "defense": 65,
            "specialAttack": 40,
            "specialDefense": 40,
            "speed": 15
        }
    },
    {
        id: 80,
        name: "Slowbro",
        filename: "080_slowbro.png",
        types: [11, 14],
        height: 16,
        weight: 785,
        stats: {
            "hp": 95,
            "attack": 75,
            "defense": 110,
            "specialAttack": 100,
            "specialDefense": 80,
            "speed": 30
        }
    },
    {
        id: 81,
        name: "Magnemite",
        filename: "081_magnemite.png",
        types: [13, 9],
        height: 3,
        weight: 60,
        stats: {
            "hp": 25,
            "attack": 35,
            "defense": 70,
            "specialAttack": 95,
            "specialDefense": 55,
            "speed": 45
        }
    },
    {
        id: 82,
        name: "Magneton",
        filename: "082_magneton.png",
        types: [13, 9],
        height: 10,
        weight: 600,
        stats: {
            "hp": 50,
            "attack": 60,
            "defense": 95,
            "specialAttack": 120,
            "specialDefense": 70,
            "speed": 70
        }
    },
    {
        id: 83,
        name: "Farfetchd",
        filename: "083_farfetchd.png",
        types: [1, 3],
        height: 8,
        weight: 150,
        stats: {
            "hp": 52,
            "attack": 90,
            "defense": 55,
            "specialAttack": 58,
            "specialDefense": 62,
            "speed": 60
        }
    },
    {
        id: 84,
        name: "Doduo",
        filename: "084_doduo.png",
        types: [1, 3],
        height: 14,
        weight: 392,
        stats: {
            "hp": 35,
            "attack": 85,
            "defense": 45,
            "specialAttack": 35,
            "specialDefense": 35,
            "speed": 75
        }
    },
    {
        id: 85,
        name: "Dodrio",
        filename: "085_dodrio.png",
        types: [1, 3],
        height: 18,
        weight: 852,
        stats: {
            "hp": 60,
            "attack": 110,
            "defense": 70,
            "specialAttack": 60,
            "specialDefense": 60,
            "speed": 110
        }
    },
    {
        id: 86,
        name: "Seel",
        filename: "086_seel.png",
        types: [11],
        height: 11,
        weight: 900,
        stats: {
            "hp": 65,
            "attack": 45,
            "defense": 55,
            "specialAttack": 45,
            "specialDefense": 70,
            "speed": 45
        }
    },
    {
        id: 87,
        name: "Dewgong",
        filename: "087_dewgong.png",
        types: [11, 15],
        height: 17,
        weight: 1200,
        stats: {
            "hp": 90,
            "attack": 70,
            "defense": 80,
            "specialAttack": 70,
            "specialDefense": 95,
            "speed": 70
        }
    },
    {
        id: 88,
        name: "Grimer",
        filename: "088_grimer.png",
        types: [4],
        height: 9,
        weight: 300,
        stats: {
            "hp": 80,
            "attack": 80,
            "defense": 50,
            "specialAttack": 40,
            "specialDefense": 50,
            "speed": 25
        }
    },
    {
        id: 89,
        name: "Muk",
        filename: "089_muk.png",
        types: [4],
        height: 12,
        weight: 300,
        stats: {
            "hp": 105,
            "attack": 105,
            "defense": 75,
            "specialAttack": 65,
            "specialDefense": 100,
            "speed": 50
        }
    },
    {
        id: 90,
        name: "Shellder",
        filename: "090_shellder.png",
        types: [11],
        height: 3,
        weight: 40,
        stats: {
            "hp": 30,
            "attack": 65,
            "defense": 100,
            "specialAttack": 45,
            "specialDefense": 25,
            "speed": 40
        }
    },
    {
        id: 91,
        name: "Cloyster",
        filename: "091_cloyster.png",
        types: [11, 15],
        height: 15,
        weight: 1325,
        stats: {
            "hp": 50,
            "attack": 95,
            "defense": 180,
            "specialAttack": 85,
            "specialDefense": 45,
            "speed": 70
        }
    },
    {
        id: 92,
        name: "Gastly",
        filename: "092_gastly.png",
        types: [8, 4],
        height: 13,
        weight: 1,
        stats: {
            "hp": 30,
            "attack": 35,
            "defense": 30,
            "specialAttack": 100,
            "specialDefense": 35,
            "speed": 80
        }
    },
    {
        id: 93,
        name: "Haunter",
        filename: "093_haunter.png",
        types: [8, 4],
        height: 16,
        weight: 1,
        stats: {
            "hp": 45,
            "attack": 50,
            "defense": 45,
            "specialAttack": 115,
            "specialDefense": 55,
            "speed": 95
        }
    },
    {
        id: 94,
        name: "Gengar",
        filename: "094_gengar.png",
        types: [8, 4],
        height: 15,
        weight: 405,
        stats: {
            "hp": 60,
            "attack": 65,
            "defense": 60,
            "specialAttack": 130,
            "specialDefense": 75,
            "speed": 110
        }
    },
    {
        id: 95,
        name: "Onix",
        filename: "095_onix.png",
        types: [6, 5],
        height: 88,
        weight: 2100,
        stats: {
            "hp": 35,
            "attack": 45,
            "defense": 160,
            "specialAttack": 30,
            "specialDefense": 45,
            "speed": 70
        }
    },
    {
        id: 96,
        name: "Drowzee",
        filename: "096_drowzee.png",
        types: [14],
        height: 10,
        weight: 324,
        stats: {
            "hp": 60,
            "attack": 48,
            "defense": 45,
            "specialAttack": 43,
            "specialDefense": 90,
            "speed": 42
        }
    },
    {
        id: 97,
        name: "Hypno",
        filename: "097_hypno.png",
        types: [14],
        height: 16,
        weight: 756,
        stats: {
            "hp": 85,
            "attack": 73,
            "defense": 70,
            "specialAttack": 73,
            "specialDefense": 115,
            "speed": 67
        }
    },
    {
        id: 98,
        name: "Krabby",
        filename: "098_krabby.png",
        types: [11],
        height: 4,
        weight: 65,
        stats: {
            "hp": 30,
            "attack": 105,
            "defense": 90,
            "specialAttack": 25,
            "specialDefense": 25,
            "speed": 50
        }
    },
    {
        id: 99,
        name: "Kingler",
        filename: "099_kingler.png",
        types: [11],
        height: 13,
        weight: 600,
        stats: {
            "hp": 55,
            "attack": 130,
            "defense": 115,
            "specialAttack": 50,
            "specialDefense": 50,
            "speed": 75
        }
    },
    {
        id: 100,
        name: "Voltorb",
        filename: "100_voltorb.png",
        types: [13],
        height: 5,
        weight: 104,
        stats: {
            "hp": 40,
            "attack": 30,
            "defense": 50,
            "specialAttack": 55,
            "specialDefense": 55,
            "speed": 100
        }
    },
    {
        id: 101,
        name: "Electrode",
        filename: "101_electrode.png",
        types: [13],
        height: 12,
        weight: 666,
        stats: {
            "hp": 60,
            "attack": 50,
            "defense": 70,
            "specialAttack": 80,
            "specialDefense": 80,
            "speed": 150
        }
    },
    {
        id: 102,
        name: "Exeggcute",
        filename: "102_exeggcute.png",
        types: [12, 14],
        height: 4,
        weight: 25,
        stats: {
            "hp": 60,
            "attack": 40,
            "defense": 80,
            "specialAttack": 60,
            "specialDefense": 45,
            "speed": 40
        }
    },
    {
        id: 103,
        name: "Exeggutor",
        filename: "103_exeggutor.png",
        types: [12, 14],
        height: 20,
        weight: 1200,
        stats: {
            "hp": 95,
            "attack": 95,
            "defense": 85,
            "specialAttack": 125,
            "specialDefense": 75,
            "speed": 55
        }
    },
    {
        id: 104,
        name: "Cubone",
        filename: "104_cubone.png",
        types: [5],
        height: 4,
        weight: 65,
        stats: {
            "hp": 50,
            "attack": 50,
            "defense": 95,
            "specialAttack": 40,
            "specialDefense": 50,
            "speed": 35
        }
    },
    {
        id: 105,
        name: "Marowak",
        filename: "105_marowak.png",
        types: [5],
        height: 10,
        weight: 450,
        stats: {
            "hp": 60,
            "attack": 80,
            "defense": 110,
            "specialAttack": 50,
            "specialDefense": 80,
            "speed": 45
        }
    },
    {
        id: 106,
        name: "Hitmonlee",
        filename: "106_hitmonlee.png",
        types: [2],
        height: 15,
        weight: 498,
        stats: {
            "hp": 50,
            "attack": 120,
            "defense": 53,
            "specialAttack": 35,
            "specialDefense": 110,
            "speed": 87
        }
    },
    {
        id: 107,
        name: "Hitmonchan",
        filename: "107_hitmonchan.png",
        types: [2],
        height: 14,
        weight: 502,
        stats: {
            "hp": 50,
            "attack": 105,
            "defense": 79,
            "specialAttack": 35,
            "specialDefense": 110,
            "speed": 76
        }
    },
    {
        id: 108,
        name: "Lickitung",
        filename: "108_lickitung.png",
        types: [1],
        height: 12,
        weight: 655,
        stats: {
            "hp": 90,
            "attack": 55,
            "defense": 75,
            "specialAttack": 60,
            "specialDefense": 75,
            "speed": 30
        }
    },
    {
        id: 109,
        name: "Koffing",
        filename: "109_koffing.png",
        types: [4],
        height: 6,
        weight: 10,
        stats: {
            "hp": 40,
            "attack": 65,
            "defense": 95,
            "specialAttack": 60,
            "specialDefense": 45,
            "speed": 35
        }
    },
    {
        id: 110,
        name: "Weezing",
        filename: "110_weezing.png",
        types: [4],
        height: 12,
        weight: 95,
        stats: {
            "hp": 65,
            "attack": 90,
            "defense": 120,
            "specialAttack": 85,
            "specialDefense": 70,
            "speed": 60
        }
    },
    {
        id: 111,
        name: "Rhyhorn",
        filename: "111_rhyhorn.png",
        types: [5, 6],
        height: 10,
        weight: 1150,
        stats: {
            "hp": 80,
            "attack": 85,
            "defense": 95,
            "specialAttack": 30,
            "specialDefense": 30,
            "speed": 25
        }
    },
    {
        id: 112,
        name: "Rhydon",
        filename: "112_rhydon.png",
        types: [5, 6],
        height: 19,
        weight: 1200,
        stats: {
            "hp": 105,
            "attack": 130,
            "defense": 120,
            "specialAttack": 45,
            "specialDefense": 45,
            "speed": 40
        }
    },
    {
        id: 113,
        name: "Chansey",
        filename: "113_chansey.png",
        types: [1],
        height: 11,
        weight: 346,
        stats: {
            "hp": 250,
            "attack": 5,
            "defense": 5,
            "specialAttack": 35,
            "specialDefense": 105,
            "speed": 50
        }
    },
    {
        id: 114,
        name: "Tangela",
        filename: "114_tangela.png",
        types: [12],
        height: 10,
        weight: 350,
        stats: {
            "hp": 65,
            "attack": 55,
            "defense": 115,
            "specialAttack": 100,
            "specialDefense": 40,
            "speed": 60
        }
    },
    {
        id: 115,
        name: "Kangaskhan",
        filename: "115_kangaskhan.png",
        types: [1],
        height: 22,
        weight: 800,
        stats: {
            "hp": 105,
            "attack": 95,
            "defense": 80,
            "specialAttack": 40,
            "specialDefense": 80,
            "speed": 90
        }
    },
    {
        id: 116,
        name: "Horsea",
        filename: "116_horsea.png",
        types: [11],
        height: 4,
        weight: 80,
        stats: {
            "hp": 30,
            "attack": 40,
            "defense": 70,
            "specialAttack": 70,
            "specialDefense": 25,
            "speed": 60
        }
    },
    {
        id: 117,
        name: "Seadra",
        filename: "117_seadra.png",
        types: [11],
        height: 12,
        weight: 250,
        stats: {
            "hp": 55,
            "attack": 65,
            "defense": 95,
            "specialAttack": 95,
            "specialDefense": 45,
            "speed": 85
        }
    },
    {
        id: 118,
        name: "Goldeen",
        filename: "118_goldeen.png",
        types: [11],
        height: 6,
        weight: 150,
        stats: {
            "hp": 45,
            "attack": 67,
            "defense": 60,
            "specialAttack": 35,
            "specialDefense": 50,
            "speed": 63
        }
    },
    {
        id: 119,
        name: "Seaking",
        filename: "119_seaking.png",
        types: [11],
        height: 13,
        weight: 390,
        stats: {
            "hp": 80,
            "attack": 92,
            "defense": 65,
            "specialAttack": 65,
            "specialDefense": 80,
            "speed": 68
        }
    },
    {
        id: 120,
        name: "Staryu",
        filename: "120_staryu.png",
        types: [11],
        height: 8,
        weight: 345,
        stats: {
            "hp": 30,
            "attack": 45,
            "defense": 55,
            "specialAttack": 70,
            "specialDefense": 55,
            "speed": 85
        }
    },
    {
        id: 121,
        name: "Starmie",
        filename: "121_starmie.png",
        types: [11, 14],
        height: 11,
        weight: 800,
        stats: {
            "hp": 60,
            "attack": 75,
            "defense": 85,
            "specialAttack": 100,
            "specialDefense": 85,
            "speed": 115
        }
    },
    {
        id: 122,
        name: "Mr-mime",
        filename: "122_mr-mime.png",
        types: [14, 18],
        height: 13,
        weight: 545,
        stats: {
            "hp": 40,
            "attack": 45,
            "defense": 65,
            "specialAttack": 100,
            "specialDefense": 120,
            "speed": 90
        }
    },
    {
        id: 123,
        name: "Scyther",
        filename: "123_scyther.png",
        types: [7, 3],
        height: 15,
        weight: 560,
        stats: {
            "hp": 70,
            "attack": 110,
            "defense": 80,
            "specialAttack": 55,
            "specialDefense": 80,
            "speed": 105
        }
    },
    {
        id: 124,
        name: "Jynx",
        filename: "124_jynx.png",
        types: [15, 14],
        height: 14,
        weight: 406,
        stats: {
            "hp": 65,
            "attack": 50,
            "defense": 35,
            "specialAttack": 115,
            "specialDefense": 95,
            "speed": 95
        }
    },
    {
        id: 125,
        name: "Electabuzz",
        filename: "125_electabuzz.png",
        types: [13],
        height: 11,
        weight: 300,
        stats: {
            "hp": 65,
            "attack": 83,
            "defense": 57,
            "specialAttack": 95,
            "specialDefense": 85,
            "speed": 105
        }
    },
    {
        id: 126,
        name: "Magmar",
        filename: "126_magmar.png",
        types: [10],
        height: 13,
        weight: 445,
        stats: {
            "hp": 65,
            "attack": 95,
            "defense": 57,
            "specialAttack": 100,
            "specialDefense": 85,
            "speed": 93
        }
    },
    {
        id: 127,
        name: "Pinsir",
        filename: "127_pinsir.png",
        types: [7],
        height: 15,
        weight: 550,
        stats: {
            "hp": 65,
            "attack": 125,
            "defense": 100,
            "specialAttack": 55,
            "specialDefense": 70,
            "speed": 85
        }
    },
    {
        id: 128,
        name: "Tauros",
        filename: "128_tauros.png",
        types: [1],
        height: 14,
        weight: 884,
        stats: {
            "hp": 75,
            "attack": 100,
            "defense": 95,
            "specialAttack": 40,
            "specialDefense": 70,
            "speed": 110
        }
    },
    {
        id: 129,
        name: "Magikarp",
        filename: "129_magikarp.png",
        types: [11],
        height: 9,
        weight: 100,
        stats: {
            "hp": 20,
            "attack": 10,
            "defense": 55,
            "specialAttack": 15,
            "specialDefense": 20,
            "speed": 80
        }
    },
    {
        id: 130,
        name: "Gyarados",
        filename: "130_gyarados.png",
        types: [11, 3],
        height: 65,
        weight: 2350,
        stats: {
            "hp": 95,
            "attack": 125,
            "defense": 79,
            "specialAttack": 60,
            "specialDefense": 100,
            "speed": 81
        }
    },
    {
        id: 131,
        name: "Lapras",
        filename: "131_lapras.png",
        types: [11, 15],
        height: 25,
        weight: 2200,
        stats: {
            "hp": 130,
            "attack": 85,
            "defense": 80,
            "specialAttack": 85,
            "specialDefense": 95,
            "speed": 60
        }
    },
    {
        id: 132,
        name: "Ditto",
        filename: "132_ditto.png",
        types: [1],
        height: 3,
        weight: 40,
        stats: {
            "hp": 48,
            "attack": 48,
            "defense": 48,
            "specialAttack": 48,
            "specialDefense": 48,
            "speed": 48
        }
    },
    {
        id: 133,
        name: "Eevee",
        filename: "133_eevee.png",
        types: [1],
        height: 3,
        weight: 65,
        stats: {
            "hp": 55,
            "attack": 55,
            "defense": 50,
            "specialAttack": 45,
            "specialDefense": 65,
            "speed": 55
        }
    },
    {
        id: 134,
        name: "Vaporeon",
        filename: "134_vaporeon.png",
        types: [11],
        height: 10,
        weight: 290,
        stats: {
            "hp": 130,
            "attack": 65,
            "defense": 60,
            "specialAttack": 110,
            "specialDefense": 95,
            "speed": 65
        }
    },
    {
        id: 135,
        name: "Jolteon",
        filename: "135_jolteon.png",
        types: [13],
        height: 8,
        weight: 245,
        stats: {
            "hp": 65,
            "attack": 65,
            "defense": 60,
            "specialAttack": 110,
            "specialDefense": 95,
            "speed": 130
        }
    },
    {
        id: 136,
        name: "Flareon",
        filename: "136_flareon.png",
        types: [10],
        height: 9,
        weight: 250,
        stats: {
            "hp": 65,
            "attack": 130,
            "defense": 60,
            "specialAttack": 95,
            "specialDefense": 110,
            "speed": 65
        }
    },
    {
        id: 137,
        name: "Porygon",
        filename: "137_porygon.png",
        types: [1],
        height: 8,
        weight: 365,
        stats: {
            "hp": 65,
            "attack": 60,
            "defense": 70,
            "specialAttack": 85,
            "specialDefense": 75,
            "speed": 40
        }
    },
    {
        id: 138,
        name: "Omanyte",
        filename: "138_omanyte.png",
        types: [6, 11],
        height: 4,
        weight: 75,
        stats: {
            "hp": 35,
            "attack": 40,
            "defense": 100,
            "specialAttack": 90,
            "specialDefense": 55,
            "speed": 35
        }
    },
    {
        id: 139,
        name: "Omastar",
        filename: "139_omastar.png",
        types: [6, 11],
        height: 10,
        weight: 350,
        stats: {
            "hp": 70,
            "attack": 60,
            "defense": 125,
            "specialAttack": 115,
            "specialDefense": 70,
            "speed": 55
        }
    },
    {
        id: 140,
        name: "Kabuto",
        filename: "140_kabuto.png",
        types: [6, 11],
        height: 5,
        weight: 115,
        stats: {
            "hp": 30,
            "attack": 80,
            "defense": 90,
            "specialAttack": 55,
            "specialDefense": 45,
            "speed": 55
        }
    },
    {
        id: 141,
        name: "Kabutops",
        filename: "141_kabutops.png",
        types: [6, 11],
        height: 13,
        weight: 405,
        stats: {
            "hp": 60,
            "attack": 115,
            "defense": 105,
            "specialAttack": 65,
            "specialDefense": 70,
            "speed": 80
        }
    },
    {
        id: 142,
        name: "Aerodactyl",
        filename: "142_aerodactyl.png",
        types: [6, 3],
        height: 18,
        weight: 590,
        stats: {
            "hp": 80,
            "attack": 105,
            "defense": 65,
            "specialAttack": 60,
            "specialDefense": 75,
            "speed": 130
        }
    },
    {
        id: 143,
        name: "Snorlax",
        filename: "143_snorlax.png",
        types: [1],
        height: 21,
        weight: 4600,
        stats: {
            "hp": 160,
            "attack": 110,
            "defense": 65,
            "specialAttack": 65,
            "specialDefense": 110,
            "speed": 30
        }
    },
    {
        id: 144,
        name: "Articuno",
        filename: "144_articuno.png",
        types: [15, 3],
        height: 17,
        weight: 554,
        stats: {
            "hp": 90,
            "attack": 85,
            "defense": 100,
            "specialAttack": 95,
            "specialDefense": 125,
            "speed": 85
        }
    },
    {
        id: 145,
        name: "Zapdos",
        filename: "145_zapdos.png",
        types: [13, 3],
        height: 16,
        weight: 526,
        stats: {
            "hp": 90,
            "attack": 90,
            "defense": 85,
            "specialAttack": 125,
            "specialDefense": 90,
            "speed": 100
        }
    },
    {
        id: 146,
        name: "Moltres",
        filename: "146_moltres.png",
        types: [10, 3],
        height: 20,
        weight: 600,
        stats: {
            "hp": 90,
            "attack": 100,
            "defense": 90,
            "specialAttack": 125,
            "specialDefense": 85,
            "speed": 90
        }
    },
    {
        id: 147,
        name: "Dratini",
        filename: "147_dratini.png",
        types: [16],
        height: 18,
        weight: 33,
        stats: {
            "hp": 41,
            "attack": 64,
            "defense": 45,
            "specialAttack": 50,
            "specialDefense": 50,
            "speed": 50
        }
    },
    {
        id: 148,
        name: "Dragonair",
        filename: "148_dragonair.png",
        types: [16],
        height: 40,
        weight: 165,
        stats: {
            "hp": 61,
            "attack": 84,
            "defense": 65,
            "specialAttack": 70,
            "specialDefense": 70,
            "speed": 70
        }
    },
    {
        id: 149,
        name: "Dragonite",
        filename: "149_dragonite.png",
        types: [16, 3],
        height: 22,
        weight: 2100,
        stats: {
            "hp": 91,
            "attack": 134,
            "defense": 95,
            "specialAttack": 100,
            "specialDefense": 100,
            "speed": 80
        }
    },
    {
        id: 150,
        name: "Mewtwo",
        filename: "150_mewtwo.png",
        types: [14],
        height: 20,
        weight: 1220,
        stats: {
            "hp": 106,
            "attack": 110,
            "defense": 90,
            "specialAttack": 154,
            "specialDefense": 90,
            "speed": 130
        }
    },
    {
        id: 151,
        name: "Mew",
        filename: "151_mew.png",
        types: [14],
        height: 4,
        weight: 40,
        stats: {
            "hp": 100,
            "attack": 100,
            "defense": 100,
            "specialAttack": 100,
            "specialDefense": 100,
            "speed": 100
        }
    }
];
