// AUTO-GENERATED by generate_spelling_words.py - DO NOT EDIT MANUALLY
//
// The word pool for the spelling minigame: the 447 most common Swedish
// words from commonSwedishWords.js (top 500 by frequency), minus words that
// would teach the wrong thing - subtitle junk, spoken forms whose written form
// differs, words that cannot be sounded out, and silent opening consonants.
// See the blocklists in generate_spelling_words.py for the reasoning.
//
// Every word here has a matching public/word_audio/<word>.mp3.

export const SPELLING_WORDS = [
    'du', 'att', 'inte', 'en', 'har', 'vi', 'på', 'i',
    'för', 'han', 'med', 'som', 'om', 'var', 'här', 'så',
    'den', 'kan', 'till', 'men', 'ett', 'ska', 'ni', 'av',
    'hon', 'vill', 'vet', 'nu', 'bara', 'hur', 'min', 'kommer',
    'där', 'måste', 'honom', 'gör', 'din', 'skulle', 'när', 'då',
    'kom', 'ha', 'bra', 'får', 'man', 'vara', 'oss', 'ut',
    'ta', 'er', 'göra', 'eller', 'hade', 'från', 'varför', 'alla',
    'tror', 'allt', 'henne', 'upp', 'sa', 'ingen', 'tack', 'gå',
    'in', 'igen', 'få', 'se', 'går', 'hej', 'vem', 'kanske',
    'lite', 'behöver', 'ser', 'mitt', 'aldrig', 'finns', 'än', 'inget',
    'efter', 'blir', 'ju', 'hans', 'bli', 'två', 'tillbaka', 'tar',
    'mer', 'över', 'fick', 'ditt', 'ge', 'väl', 'också', 'mina',
    'åt', 'nog', 'kunde', 'år', 'mamma', 'varit', 'ner', 'ville',
    'vänta', 'mot', 'pappa', 'andra', 'borde', 'känner', 'rätt', 'vid',
    'hela', 'såg', 'hit', 'prata', 'komma', 'låt', 'detta', 'blev',
    'tog', 'alltid', 'vår', 'utan', 'fel', 'hem', 'dina', 'liv',
    'menar', 'verkligen', 'visst', 'förstår', 'sin', 'tid', 'trodde', 'gick',
    'älskar', 'sätt', 'berätta', 'tänker', 'veta', 'tre', 'många', 'folk',
    'sluta', 'precis', 'inga', 'hennes', 'titta', 'innan', 'visste', 'gillar',
    'barn', 'bättre', 'under', 'förlåt', 'gång', 'bort', 'händer', 'just',
    'helt', 'säg', 'tycker', 'första', 'håll', 'länge', 'hör', 'sett',
    'ledsen', 'snälla', 'saker', 'hitta', 'fortfarande', 'står', 'pengar', 'god',
    'samma', 'ens', 'ursäkta', 'heter', 'håller', 'vilken', 'enda', 'våra',
    'hand', 'borta', 'mår', 'hände', 'ur', 'problem', 'vän', 'ger',
    'stanna', 'sak', 'försöker', 'låter', 'far', 'kvar', 'väg', 'annan',
    'redan', 'längre', 'pratar', 'väldigt', 'vart', 'dit', 'kväll', 'fått',
    'snart', 'ute', 'fråga', 'sitt', 'tiden', 'kör', 'deras', 'tänkte',
    'namn', 'verkar', 'tro', 'varje', 'fram', 'bästa', 'fru', 'först',
    'träffa', 'säkert', 'slut', 'hos', 'ingenting', 'därför', 'åka', 'visa',
    'säker', 'lämna', 'börjar', 'vägen', 'genom', 'gav', 'härifrån', 'jobb',
    'hålla', 'son', 'stor', 'vänner', 'hittade', 'annat', 'hoppas', 'sina',
    'hörde', 'vilket', 'kolla', 'minns', 'ihop', 'rädd', 'sista', 'även',
    'era', 'vårt', 'kunna', 'ses', 'del', 'nästa', 'fem', 'livet',
    'nya', 'människor', 'bilen', 'riktigt', 'klarar', 'höra', 'tills', 'liten',
    'betyder', 'tänk', 'tag', 'lyssna', 'polisen', 'ändå', 'hemma', 'sant',
    'fast', 'faktiskt', 'ligger', 'idag', 'minuter', 'familj', 'runt', 'blivit',
    'klart', 'fall', 'väntar', 'fyra', 'dra', 'dollar', 'åker', 'kul',
    'tala', 'illa', 'män', 'försökte', 'helst', 'annars', 'haft', 'nästan',
    'ensam', 'inne', 'lika', 'lägg', 'hittar', 'redo', 'hämta', 'jobbar',
    'gången', 'båda', 'ny', 'denna', 'stora', 'plats', 'tur', 'börja',
    'svårt', 'lugnt', 'långt', 'spelar', 'kvinna', 'känns', 'älskling', 'hänt',
    'bil', 'emot', 'låta', 'tillsammans', 'öppna', 'släpp', 'hört', 'huset',
    'senare', 'bror', 'ringer', 'lilla', 'be', 'rör', 'ibland', 'rädda',
    'heller', 'fort', 'glad', 'gått', 'mellan', 'nära', 'ifrån', 'hus',
    'vore', 'igenom', 'fler', 'kände', 'vilka', 'dotter', 'bryr', 'kille',
    'tänka', 'bor', 'fattar', 'gärna', 'fanns', 'ber', 'började', 'killen',
    'sitter', 'slå', 'ännu', 'tio', 'trevligt', 'vilja', 'gott', 'spela',
    'bäst', 'chans', 'gånger', 'varandra', 'timmar', 'lever', 'pengarna', 'äta',
    'handlar', 'natt', 'rum', 'klara', 'mor', 'gamla', 'ord', 'ihåg',
    'reda', 'ringa', 'mannen', 'ert', 'bakom', 'eftersom', 'gammal', 'jobbet',
    'dörren', 'fara', 'känna', 'dessa', 'all', 'par', 'bad', 'alls',
    'tyst', 'egen', 'kommit', 'ringde', 'klar', 'galen', 'leva', 'syster',
    'oroa', 'mat', 'vapen', 'ring', 'skull', 'stället', 'antar', 'tagit',
    'sätta', 'stå', 'berättade', 'ganska', 'följer', 'klockan', 'tidigare', 'hittat',
    'följa', 'räcker', 'fint', 'lätt', 'försöka', 'lång', 'lovar', 'förut',
    'jobba', 'skolan', 'iväg', 'letar', 'ikväll', 'flera', 'försök'
];

// The first `count` words, i.e. the most common ones. Lets the pool be narrowed
// from the admin panel without regenerating any audio.
export function getSpellingWords(count) {
    const n = Math.max(1, Math.min(count || SPELLING_WORDS.length, SPELLING_WORDS.length));
    return SPELLING_WORDS.slice(0, n);
}
